name: Test
runs-on: ubuntu-latest

strategy:
  matrix:
    node-version: [14.x, 16.x]

steps:
  - name: Checkout
    uses: actions/checkout@v2
    with:
      fetich-depth: 0

  - name: Use Node.JS ${{ matrix.node-version }}
    uses: actions/setup-node@v2
    with:
      node-version: ${{ matrix.node-version }}

  - name: NPM install, build and test
    run: |
      npm install
      npm test
